language: csharp
dist: trusty
matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 2.1.2
      mono: none
    - os: osx
      dotnet: 2.1.2
      mono: none
script:
  - |
    cd src
    dotnet sln SpecificationDemo.sln remove SpecificationDemoBddTest/SpecificationDemoBddTest.csproj
    dotnet restore
    dotnet build
    cd ..
after_success:
  - |
    cd src
    dotnet test SpecificationDemoXunitTest
    cd ..